# Generated by Django 5.1.1 on 2024-09-20 04:48

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('background_color', models.CharField(blank=True, choices=[('bg-transparent', 'Transparent'), ('bg-base-100', 'Base-100'), ('bg-base-200', 'Base-200'), ('bg-base-300', 'Base-300'), ('bg-base-content', 'Base Content'), ('bg-primary', 'Primary'), ('bg-primary-content', 'Primary Content'), ('bg-secondary', 'Secondary'), ('bg-secondary-content', 'Secondary Content'), ('bg-accent', 'Accent'), ('bg-accent-content', 'Accent Content'), ('bg-neutral', 'Neutral'), ('bg-neutral-content', 'Neutral Content'), ('bg-info', 'Info'), ('bg-info-content', 'Info Content'), ('bg-success', 'Success'), ('bg-success-content', 'Success Content'), ('bg-warning', 'Warning'), ('bg-warning-content', 'Warning Content'), ('bg-error', 'Error'), ('bg-error-content', 'Error Content')], default=None, max_length=31, null=True)),
                ('foreground_color', models.CharField(blank=True, choices=[('text-base-100', 'Base-100'), ('text-base-200', 'Base-200'), ('text-base-300', 'Base-300'), ('text-base-content', 'Base Content'), ('text-primary', 'Primary'), ('text-primary-content', 'Primary Content'), ('text-secondary', 'Secondary'), ('text-secondary-content', 'Secondary Content'), ('text-accent', 'Accent'), ('text-accent-content', 'Accent Content'), ('text-neutral', 'Neutral'), ('text-neutral-content', 'Neutral Content'), ('text-info', 'Info'), ('text-info-content', 'Info Content'), ('text-success', 'Success'), ('text-success-content', 'Success Content'), ('text-warning', 'Warning'), ('text-warning-content', 'Warning Content'), ('text-error', 'Error'), ('text-error-content', 'Error Content')], default=None, max_length=31, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
        migrations.CreateModel(
            name='ButtonModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(blank=True, default=None, max_length=127, null=True)),
                ('external', models.URLField(blank=True, default=None, max_length=2047, null=True)),
                ('type', models.CharField(blank=True, choices=[('link', 'Plain Link'), ('btn', 'Button')], default=None, max_length=15, null=True)),
                ('color', models.CharField(blank=True, choices=[('btn-ghost', 'Transparent'), ('btn-primary', 'Primary'), ('btn-secondary', 'Secondary'), ('btn-accent', 'Accent'), ('btn-neutral', 'Neutral'), ('btn-info', 'Info'), ('btn-success', 'Success'), ('btn-warning', 'Warning'), ('btn-error', 'Error')], default=None, max_length=15, null=True)),
                ('size', models.CharField(blank=True, choices=[('btn-md', 'Standard'), ('btn-lg', 'Large'), ('btn-sm', 'Small'), ('btn-xs', 'Extra Small')], default=None, max_length=15, null=True)),
                ('variant', models.CharField(blank=True, choices=[('btn-wide', 'Wide'), ('btn-block', 'Block'), ('btn-circle', 'Circle'), ('btn-square', 'Square')], default=None, max_length=15, null=True)),
                ('glass_design', models.BooleanField(blank=True, default=False)),
                ('outline_only', models.BooleanField(blank=True, default=False)),
                ('use_child_plugins', models.BooleanField(blank=True, default=False)),
                ('internal', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.pagecontent')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('scale_type', models.CharField(blank=True, choices=[('object-contain', 'Contain'), ('object-cover', 'Cover'), ('object-fill', 'Fill'), ('object-scale-down', 'Scale Down')], default=None, max_length=31, null=True)),
                ('width', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('height', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('alt_text', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('image', filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL)),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
