# Generated by Django 5.1.1 on 2024-09-20 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bro_theme', '0001_initial'),
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('start_level', models.IntegerField(blank=True, default=0)),
                ('end_level', models.IntegerField(blank=True, default=100)),
                ('extra_inactive', models.IntegerField(blank=True, default=2)),
                ('extra_active', models.IntegerField(blank=True, default=2)),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
