# Generated by Django 5.0.8 on 2024-09-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bro_theme', '0002_menumodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionmodel',
            name='is_full_width',
            field=models.BooleanField(default=False),
        ),
    ]
