# Generated by Django 5.0.8 on 2024-09-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bro_theme', '0003_sectionmodel_is_full_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionmodel',
            name='is_inner',
            field=models.BooleanField(default=False),
        ),
    ]
