# Generated by Django 5.0.8 on 2024-10-06 04:18

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bro_theme', '0005_footermenumodel'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionmodel',
            name='alt_text',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='height',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='scale_type',
            field=models.CharField(blank=True, choices=[('object-contain', 'Contain'), ('object-cover', 'Cover'), ('object-fill', 'Fill'), ('object-scale-down', 'Scale Down')], default=None, max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='width',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
