# Generated by Django 5.0.8 on 2024-10-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bro_theme', '0006_sectionmodel_alt_text_sectionmodel_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='apply_rounding',
            field=models.BooleanField(default=True),
        ),
    ]
