# Generated by Django 5.0.8 on 2024-10-09 01:58

import django.db.models.deletion
import filer.fields.file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bro_theme', '0007_imagemodel_apply_rounding'),
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('filer', '0017_image__transparent'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('autoplay', models.BooleanField(default=False)),
                ('controls', models.BooleanField(default=False)),
                ('loop', models.BooleanField(default=False)),
                ('muted', models.BooleanField(default=False)),
                ('width', models.CharField(default='', max_length=31)),
                ('height', models.CharField(default='', max_length=31)),
                ('video', filer.fields.file.FilerFileField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='filer.file')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
