# Generated by Django 5.0.8 on 2024-10-09 02:07

import django.db.models.deletion
import filer.fields.file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bro_theme', '0008_videomodel'),
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('filer', '0017_image__transparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='autoplay',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='controls',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='height',
            field=models.CharField(blank=True, default='', max_length=31),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='loop',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='muted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='width',
            field=models.CharField(blank=True, default='', max_length=31),
        ),
        migrations.CreateModel(
            name='VideoHeroSectionModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('background_color', models.CharField(blank=True, choices=[('bg-transparent', 'Transparent'), ('bg-base-100', 'Base-100'), ('bg-base-200', 'Base-200'), ('bg-base-300', 'Base-300'), ('bg-base-content', 'Base Content'), ('bg-primary', 'Primary'), ('bg-primary-content', 'Primary Content'), ('bg-secondary', 'Secondary'), ('bg-secondary-content', 'Secondary Content'), ('bg-accent', 'Accent'), ('bg-accent-content', 'Accent Content'), ('bg-neutral', 'Neutral'), ('bg-neutral-content', 'Neutral Content'), ('bg-info', 'Info'), ('bg-info-content', 'Info Content'), ('bg-success', 'Success'), ('bg-success-content', 'Success Content'), ('bg-warning', 'Warning'), ('bg-warning-content', 'Warning Content'), ('bg-error', 'Error'), ('bg-error-content', 'Error Content')], default=None, max_length=31, null=True)),
                ('foreground_color', models.CharField(blank=True, choices=[('text-base-100', 'Base-100'), ('text-base-200', 'Base-200'), ('text-base-300', 'Base-300'), ('text-base-content', 'Base Content'), ('text-primary', 'Primary'), ('text-primary-content', 'Primary Content'), ('text-secondary', 'Secondary'), ('text-secondary-content', 'Secondary Content'), ('text-accent', 'Accent'), ('text-accent-content', 'Accent Content'), ('text-neutral', 'Neutral'), ('text-neutral-content', 'Neutral Content'), ('text-info', 'Info'), ('text-info-content', 'Info Content'), ('text-success', 'Success'), ('text-success-content', 'Success Content'), ('text-warning', 'Warning'), ('text-warning-content', 'Warning Content'), ('text-error', 'Error'), ('text-error-content', 'Error Content')], default=None, max_length=31, null=True)),
                ('autoplay', models.BooleanField(blank=True, default=False)),
                ('controls', models.BooleanField(blank=True, default=False)),
                ('loop', models.BooleanField(blank=True, default=False)),
                ('muted', models.BooleanField(blank=True, default=False)),
                ('width', models.CharField(blank=True, default='', max_length=31)),
                ('height', models.CharField(blank=True, default='', max_length=31)),
                ('is_full_width', models.BooleanField(default=False)),
                ('is_inner', models.BooleanField(default=False)),
                ('video', filer.fields.file.FilerFileField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='filer.file')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
    ]
