# Generated by Django 5.0.8 on 2024-09-15 10:17

import cms.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bro_frontend', '0005_linkmodel'),
        ('cms', '0035_auto_20230822_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmodel',
            name='label',
            field=models.CharField(default='', max_length=127),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='link',
            field=cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page'),
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='type',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('btn', 'Button'), ('link', 'Link')], default='', max_length=63),
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='variant',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('btn-primary', 'Primary Button'), ('btn-secondary', 'Secondary Button'), ('btn-accent', 'Accent Button'), ('btn-info', 'Info Button'), ('btn-success', 'Success Button'), ('btn-warning', 'Warning Button'), ('btn-error', 'Error Button'), ('btn-link', 'Link Button')], default='', max_length=63),
        ),
    ]
