# Generated by Django 5.0.8 on 2024-09-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bro_frontend', '0006_linkmodel_label_alter_linkmodel_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmodel',
            name='size',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('btn-sm', 'Default'), ('btn-lg', 'Default'), ('btn-xl', 'Default')], default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='label',
            field=models.CharField(blank='', max_length=127),
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='type',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('btn', 'Button'), ('link', 'Link')], default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='variant',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('btn-primary', 'Primary Button'), ('btn-secondary', 'Secondary Button'), ('btn-accent', 'Accent Button'), ('btn-info', 'Info Button'), ('btn-success', 'Success Button'), ('btn-warning', 'Warning Button'), ('btn-error', 'Error Button'), ('btn-link', 'Link Button')], default='', max_length=15),
        ),
    ]
