# Generated by Django 5.0.8 on 2024-09-15 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bro_frontend', '0007_linkmodel_size_alter_linkmodel_label_and_more'),
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.pagecontent'),
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='size',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('btn-sm', 'Small'), ('btn-lg', 'Large')], default='', max_length=7),
        ),
    ]
