# Generated by Django 5.0.8 on 2024-09-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bro_frontend', '0008_alter_linkmodel_link_alter_linkmodel_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosectionimagemodel',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='herosectionimagemodel',
            name='summary',
        ),
    ]
