# Generated by Django 5.0.2 on 2024-09-18 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0037_alter_cmsplugin_id_alter_globalpagepermission_id_and_more'),
        ('flow_theme', '0002_titledsectionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowLinkModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('external_link', models.CharField(blank=True, default='', max_length=1023)),
                ('internal_link', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.pagecontent')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
