# Generated by Django 5.0.2 on 2024-09-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_theme', '0003_flowlinkmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowlinkmodel',
            name='label',
            field=models.CharField(blank=True, default=None, max_length=1023, null=True),
        ),
    ]
